_extern_c_backupCursor:
    jmp 0x1000:0x001e
_extern_c_blankScreen:
    jmp 0x1000:0x03b6
_extern_c_strlen:
    jmp 0x1000:0x00ba
_extern_c_main:
    jmp 0x1000:0x0412
_extern_c_getkey:
    jmp 0x1000:0x0155
_extern_c_repl:
    jmp 0x1000:0x02ea
_extern_c_strcmp:
    jmp 0x1000:0x0265
_extern_c_advanceCursor:
    jmp 0x1000:0x0067
_extern_c_setCursorPosition:
    jmp 0x1000:0x0000
_extern_c_memset:
    jmp 0x1000:0x0227
_extern_c_putc:
    jmp 0x1000:0x00a0
_extern_c_puts:
    jmp 0x1000:0x00f4
_extern_c_gets:
    jmp 0x1000:0x017b
