
_extern_c__cgets:
    jmp 0x1000:0x212

_extern_c__putch:
    jmp 0x1000:0x15c

_extern_c_basic_solve_expr:
    jmp 0x1000:0x750

_extern_c_memcpy:
    jmp 0x1000:0x344

_extern_c_islower:
    jmp 0x1000:0x595

_extern_c_dtoa:
    jmp 0x1000:0x478

_extern_c__cputs:
    jmp 0x1000:0x184

_extern_c_basic_print_var:
    jmp 0x1000:0xe94

_extern_c_isxdigit:
    jmp 0x1000:0x5f3

_extern_c__getkey:
    jmp 0x1000:0x1fd

_extern_c__start:
    jmp 0x1000:0x108e

_extern_c_isupper:
    jmp 0x1000:0x578

_extern_c_blankScreen:
    jmp 0x1000:0x0

_extern_c_setCursorPosition:
    jmp 0x1000:0x5c

_extern_c_strncat:
    jmp 0x1000:0x3a7

_extern_c_memset:
    jmp 0x1000:0x306

_extern_c_basic_repl:
    jmp 0x1000:0xeee

_extern_c_isalnum:
    jmp 0x1000:0x5b2

_extern_c_strcmp:
    jmp 0x1000:0x401

_extern_c_basic_parse_expr:
    jmp 0x1000:0xa33

_extern_c__tokenize:
    jmp 0x1000:0x647

_extern_c_advanceCursor:
    jmp 0x1000:0x104

_extern_c_isdigit:
    jmp 0x1000:0x55b

_extern_c_atoi:
    jmp 0x1000:0x4dd

_extern_c_strlen:
    jmp 0x1000:0x2d1

_extern_c_backupCursor:
    jmp 0x1000:0x94

_extern_c__tokenizer_init:
    jmp 0x1000:0x62e

